services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=myuser'
    ports:
      - '61981:3306'