services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    expose:
      - "3306"